### ISSUE TITLE
Thermal sensation question

### ISSUE THREAD

**Issue by FedericoTartarini** [buds-lab/cozie-examples#2]
I believe currently there is only a thermal preference question, it would be nice to add a thermal sensation question. (i.e. Rate your current thermal sensation: Hot, Cold and Neutral)

**Comment by pjayathissa** [comment]
Would you be able to explain the difference between the two?

If I feel cold, wouldn't I prefer it warmer? Aren't they redundant questions?

**Comment by FedericoTartarini** [comment]
The two questions are not exactly the same (thermal sensation and thermal preference). By asking both questions we could:
1. filter out people who respond without thinking and they say I am "Hot" and I want to "Be Hotter". This methodology is not always 100% accurate since some people may be feeling comfortably"Warm" (like after walking indoor from a cold space and still wanting to be hotter).
2. in addition we could better understand how people like their environment. For example they may be Neutral with the environment but they want it to be colder or warmer since the want some stimuli. (like a white room is neutral but we may want some color in it which give us some stimuli)
3. finally it could help us with controlling the building. In this case the help would be marginal since we are using a three point scale, but let's assume we could ask their thermal sensation vote on a 7-point scale. A person wanting cooler that was slightly warm is only slightly off his thermal neutrality so we may not take any actions. While if the person vote he want cooler since he is hot, would imply that the building needs to change the set point.

While the last two points may not be relevant at this stage, asking two questions would still be useful to address point 1. By doing so we could commit an error in some instances but overall we could significantly improve the quality of the data.

**Comment by FedericoTartarini** [comment]
We decided not to include this question
