### ISSUE TITLE
Clothing question

### ISSUE THREAD

**Issue by FedericoTartarini** [buds-lab/cozie-examples#4]
We could add a fourth icon representing very light clothing(panties and tan-top) 
![image](https://user-images.githubusercontent.com/40018640/67060965-5af3f480-f191-11e9-90c0-12d15755cdd3.png)

**Comment by pjayathissa** [comment]
Do you have an svg of that drawing?

**Comment by FedericoTartarini** [comment]
No I only have the .png. We can download similar icons from [here](https://www.flaticon.com/search?word=clothing) or I could generate .svg images which are in line with the format (color and style) of the other questions.
