### ISSUE TITLE
Activity level

### ISSUE THREAD

**Issue by FedericoTartarini** [buds-lab/cozie-examples#5]
We could also consider asking a question regarding their activity level. I know we could to some extend infer this information from the accelererometer data and the heart rate data, however, in some cases it would be useful to have this information.

**Comment by pjayathissa** [comment]
What would the questions be in this situation?

**Comment by FedericoTartarini** [comment]
![image](https://user-images.githubusercontent.com/40018640/67269222-e5698a80-f4e8-11e9-9b0d-5e32647fc894.png)
