### ISSUE TITLE
Previous activity

### ISSUE THREAD

**Issue by FedericoTartarini** [buds-lab/cozie-examples#6]
I think would be very important to add a question regarding their location and activity over previous 15 minutes. For example we could ask: 

Over the previous 15 minutes have you:
- changed your location?
- activity level?

YES or NO

**Comment by pjayathissa** [comment]
Could we do this using the step counter? 

We have access to the amount of steps walked in the past 15min for example

**Comment by FedericoTartarini** [comment]
We could but eventually is not the same thing. For example, we may not capture this if the person was previously laying on the bed (0.8 met) and now is studying at his desk (1.1-1.2 met). See how much the comfort region moves by just changing the met value. Please use this [tool](https://shrouded-refuge-24438.herokuapp.com)
