### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by FedericoTartarini** [buds-lab/cozie-examples#7]
We could also add custom push notifications that invite the user to complete the survey.

For example, we could use the Telegram boot to send a message when we would like the user to complete the survey (e.g. at a certain time of the day, during a hot/cold day, etc.)

**Comment by pjayathissa** [comment]
@matiRLC FYI, this is not for now, but a future implementation

**Comment by FedericoTartarini** [comment]
Done
